services:
  mongodb:
    container_name: mongodb
    image: mongo
    command: mongod --port 27018
    volumes:
      - './data/db:/data/db'
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27018"

  crawlers:
    container_name: mev_crawlers
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27018/mev?authSource=admin
